name: "\U0001F41B Bug Report"
description: "Report a reproducible bug in the Project."
body:
- type: markdown
  attributes:
  value: |
  Thanks for taking the time to file a bug report! Before filling out a new issue, please first check to see if your question has been answered in an existing issue, or in the project documentation at [https://example.com](https://example.com)

      **Please note** The project is supported for free on a voluntary basis. If you use the project please [sponsor the project](https://github.com/sponsors/MrVitaly) so that its development can continue. Bug reports from sponsors will be prioritised.
      
      Please take the time to fill in this form as completely as possible. If you leave out sections there is a high likelihood your issue will be closed.
